
name: NX_CI

on:
  push:
    branches:
      - master
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: Extract owner and repo
      uses: jungwinter/split@v2
      id: repo
      with:
        seperator: /
        msg: ${{ github.repository }}
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: cd example && make -j2
# jobs:
  # build_NX:
  #     runs-on: ubuntu-latest
    
  #     steps:
  #       - name: Extract owner and repo
  #         uses: jungwinter/split@v1
  #         id: repo
  #         with:
  #           seperator: /
  #           msg: ${{ github.repository }}
  #       - name: Checkout
  #         uses: actions/checkout@v2
  #         with:
  #           ref: master
  #           submodules: recursive
  #       - name: Use Docker Build
  #         uses: actions-hub/docker/cli@master
  #         env:
  #             SKIP_LOGIN: true
  #       - run: |
  #              docker run -t --rm --name builder -v `pwd`:`pwd` -w `pwd` zerofo/ns_dev:0.4 make
  #              mkdir -p switch/.overlays/
  #              cp *.ovl switch/.overlays/
  #              zip -r fastCFWSwitch.zip switch
    - name: Upload file
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.repo.outputs._1 }} 
        path: fastCFWSwitch.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.release_token }}
        file: fastCFWSwitch.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
